{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
{{- if and .Values.global.ingress.proAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-pro-auth
spec:
  forwardAuth:
    address: {{ include "app.proAuthAddress" . }}
    trustForwardHeader: false
    authResponseHeaders:
      - Authorization
{{- end }}
{{- end }}